DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS users;

CREATE TABLE messages(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userId INT NOT NULL,
	body TEXT NOT NULL
);

CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

INSERT INTO users (name)
VALUES ('George');

INSERT INTO messages (userId, body)
VALUES (1, 'Hi George!');
